import pygame
from time import sleep
pygame.init()
window=pygame.display.set_mode((0,0),pygame.FULLSCREEN)
pygame.mixer.init()
pygame.mixer.music.load("horror.mp3")
pygame.mixer.music.play()
sleep(2)
pygame.mixer.music.load("bhoot.mp3")
pygame.mixer.music.play()
sleep(1)
image=pygame.image.load("gst.jpg")
window.blit(image,(0,0))
pygame.display.update()
sleep(1)